version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/containers/api.prod.Dockerfile
    container_name: trello_api
    volumes:
      - .:/trello
      - ../static:/static
      - ../media:/media
    command: trello/docker/scripts/api.entrypoint.prod.sh
    env_file:
      - ./docker/envs/.env-prod
#    ports:
#      - "8000:8000"
    network_mode: "host"